CREATE DABATASE IF NOT EXISTS `newrich` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `newrich`;

CREATE TABLE `forms` (
    `id` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `fields` TEXT NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `form_fields` (
    `id` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `form_id` INT(11) UNSIGNED NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `type` VARCHAR(255) NOT NULL,
    `label` VARCHAR(255) NOT NULL,
    `rules` TEXT NOT NULL,
    `email` TINYINT(1) NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `FK_form_fields_forms` FOREIGN KEY (`form_id`) REFERENCES `forms` (`id`) ON DELETE CASCADE
);

CREATE TABLE `form_submissions` (
    `id` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `form_id` INT(11) UNSIGNED NOT NULL,
    `data` TEXT NOT NULL,
    `submitted_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT `FK_form_submissions_forms` FOREIGN KEY (`form_id`) REFERENCES `forms` (`id`) ON DELETE CASCADE
);

